version: "3.9"

x-logging: &logging
 driver: "json-file"
 options:
   max-size: "1000m"
   max-file: "1"

services:
  # Имидж сервиса вэб приложения собранный из докер-файла. Указываем проброс порта,
  # сеть типа bridge, зависимость запуска от сервиса redis, YAML anchors для
  # снижения муссора из логов
  web:
    build: .
    ports:
    - "127.0.0.1:${WEB_PORT}:5000"
    networks:
    - net
    depends_on:
      redis:
        condition: service_healthy
    logging: *logging

  # Имидж сервиса Redis взятый готовым из риджестри. Указываем сеть типа bridge,
  # волюм redis, профиль для запуска, лимиты по CPU и RAM, YAML anchors для
  # снижения муссора из логов. Для запуска контейнеров, понадобится указать 
  # профиль: docker compose --profile redis up
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
    - net
    volumes:
    - redis_data:/data
    logging: *logging
    profiles: ["redis"]
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    
networks:
  net:
    driver: bridge

volumes:
  redis_data:
